### ISSUE TITLE
Unhandled exception if 'Connect to Unity' option on 2nd instance of commands editor is checked

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#293]
Often I will have commands editor open for Steam and another for Epic.  If Unity is enabled on one instance and I check 
it on the other one it throws an error "Failed to Initialise Unity Connection".    
I expect this since we can obviously have only one connection at a time.  I did not actually mean to click the Unity option.  
The mouse was over the wrong option when I clicked.  I would not bother to report it at all since the initial error is fine except
it went on to throw this unhandled exception too. 

This is something that will rarely show up, but we were talking on discord about using multiple instances of the commands editor.    
So others might see it if they make a similar mistake.

```
===========
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CommandsEditor.CommandsEditor.SendWebsocketData(WSPacket content)
   at CommandsEditor.CommandsEditor.RefreshWebsocket(Object o)
   at CommandsEditor.CommandsEditor.RefreshWebsocket()
   at CommandsEditor.CommandsEditor.connectToUnity_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CommandsEditor
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
DiscordRPC
    Assembly Version: 1.2.1.24
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
CathodeLib
    Assembly Version: 0.5.1.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
websocket-sharp
    Assembly Version: 1.0.2.19803
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
ST.Library.UI
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Program%20Files/Epic%20Games/AlienIsolation/DATA/MODTOOLS/REMOTE_ASSETS/scripteditor/CommandsEditor.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by MattFiler** [comment]
Will push a fix for this to staging shortly.

**Comment by ghramsey** [comment]
I have not seen this bug since it initially cropped up.   

I think it's solved. I tried triggering Unity on both instances and did not 
receive the exceptijn only the expected mesage.
