### ISSUE TITLE
Forced autoupdate breaks the tool and it fails to launch.

### ISSUE THREAD

**Issue by Dushess** [MattFiler/OpenCAGE#47]
![image](https://user-images.githubusercontent.com/15954961/131920790-2e17e925-c25b-4cda-ba8d-02deeabd64af.png)

Today launched it (at PC and a laptop, 1st changed hardware config and maybe some system components, you know. Laptop has absolutely same state than before). The result is above, and next is log from the report:

```
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   в Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   в Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   в Newtonsoft.Json.Linq.JObject.Parse(String json)
   в Updater.Updater.<>c__DisplayClass5_0.<Updater_Load>b__1(Object s, AsyncCompletedEventArgs clientprogress)
   в System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   в System.Net.WebClient.DownloadFileOperationCompleted(Object arg)


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OpenCAGE Updater
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///F:/GAMES/Steam/steamapps/common/Alien%20Isolation/OpenCAGE%20Updater.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Версия сборки: 12.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///F:/GAMES/Steam/steamapps/common/Alien%20Isolation/OpenCAGE%20Updater.exe
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
```

**Comment by Dushess** [comment]
Base page link gives me just a tool exe, not archive. But it has autoupdate and it tries to download broken version. 2nd time I've launched it and now I have deleted vile, CAGEupdater instead, which acts same way. Why I can't use youк tool and don't have technical issues to solve?

**Comment by stephen-hill** [comment]
Hi

I too am getting the same problem.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Updater.Updater.<>c__DisplayClass5_0.<Updater_Load>b__1(Object s, AsyncCompletedEventArgs clientprogress)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.DownloadFileOperationCompleted(Object arg)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OpenCAGE Updater
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/OpenCAGE%20Updater.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/OpenCAGE%20Updater.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

I've made sure there are no MOD or MODTOOLS directories under DATA.

I added

```
"CONFIG_SkipUpdateCheck": true
```

to OpenCAGE Settings.json but this appears to be ignored.

Looking at the code that decides if an update should be done [https://github.com/MattFiler/OpenCAGE/blob/master/Source/OpenCAGE/UpdateManager.cs#L27] (unless I'm mis-understanding the code, my C# is rusty) it looks like it only taking the first 4 characters which would be "0.9." instead of the first 7 characters.

When I check the contents of assets.manifest on the disk, it's empty, suggesting it's not downloading. Maybe Github is blocking the useragent?

As it stands, I cannot get this mod tool running.

I do think that updating should be optional.

Thank you

**Comment by MattFiler** [comment]
Thanks for the info dump. Will look into this further.

**Comment by MattFiler** [comment]
@stephen-hill Please could you give the latest [staging build](https://github.com/MattFiler/OpenCAGE/raw/d09b6d502ac8b49ff3133b4877d0609b03311473/OpenCAGE.exe) of OpenCAGE a try and see if your issue is fixed?

**Comment by stephen-hill** [comment]
I now get the following error message
![image](https://user-images.githubusercontent.com/205619/154821711-7c8c4543-eaed-4fb3-8764-2c06fba66496.png)

**Comment by MattFiler** [comment]
@stephen-hill Sweet, could you try the [latest build](https://github.com/MattFiler/OpenCAGE/raw/staging/OpenCAGE.exe) again and see if it's fixed? Seems to be a Windows 7 TLS version issue, which should hopefully now be mitigated.

**Comment by stephen-hill** [comment]
@MattFiler Perfect :)
